spring:
  cloud:
    gateway:
      routes:
        - id: msauthorization
          uri: lb://ms-authorization
          predicates:
            - Path=/oauth/**
          filters:
            - LoggingFilter
            - GlobalErrorFilter
        - id: mspersons
          uri: lb://ms-persons
          predicates:
            - Path=/persons/**
          filters:
            - LoggingFilter
            - GlobalErrorFilter
        - id: msstore
          uri: lb://ms-store
          predicates:
            - Path=/store/**
          filters:
            - LoggingFilter
            - GlobalErrorFilter